; ========================================
; PlatformIO Project Configuration
; Cifru Electronic Seif
; ========================================

[env:uno]
platform = atmelavr
board = uno
framework = arduino

; Port COM pentru upload
upload_port = COM4
monitor_port = COM4
monitor_speed = 9600

; Biblioteca pentru tastatura
lib_deps = 
    keypad